### ISSUE TITLE
Please provide an installation guide in the README

### ISSUE THREAD

**Issue by szarnyasg** [DevBoost/JaMoPP#30]
The JaMoPP page has quite a few broken links.
After some trial-and-error, I managed to install EMFText and JaMoPP from the following update sites:

* http://update.emftext.org/trunk/
* http://update.jamopp.org/trunk/

Can you please list these in the README? Thanks!

**Comment by mirkoseifert** [comment]
Done.

**Comment by szarnyasg** [comment]
Thanks!
