### ISSUE TITLE
M2M transformation - Trouble generating Java code

### ISSUE THREAD

**Issue by RuthOjo** [DevBoost/JaMoPP#31]
I am having trouble generating Java code with JaMoPP, given my sample
model transformation output file, as input for the code generation.

I have looked though and ran the sample ATL project on the
DevBoost JaMoPP Github repository and I see it produces the src-gen
folder and an empty java file. When I use similar run configuration
settings for my project I only obtain an empty java file.

I had also looked through a basic tutorial on running JaMoPP from:
primordion.com/Xholon/wiki/JaMoPP_Basic_Tutorial/
http://primordion.com/Xholon/wiki/JaMoPP_Basic_Tutorial/
On running the given code with my project specific files and I get errors at the point where the Java file is to be created.

Given the above I hope you can assist me with the following:
1. Is there any detailed documentation on how to run the JaMoPP ATL
sample project?
1. Are there any other resources that have more detail on how to
   generate code with JaMoPP from a model transformation?

**Comment by jjohannes** [comment]
I tried the ATL example some weeks ago to reproduce another issue and it still worked for me.

Maybe this can help you to get started:
https://github.com/DevBoost/JaMoPP/issues/28#issuecomment-126482155
