### ISSUE TITLE
Project website is down

### ISSUE THREAD

**Issue by mkonersmann** [DevBoost/JaMoPP#36]
The project website jamopp.org seems to be down at the moment.
Opening jamopp.org currently returns:

> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><body>
> <h1>Forbidden</h1>
> <p>You don't have permission to access /
> on this server.</p>
> </body></html>

**Comment by mirkoseifert** [comment]
We are aware of that. This is intentional since the project website did not conform to the DSGVO regulations. @jreimone and @jjohannes are working on the transfer of the website content to GitHub so it is accessible again.
